(function(){
'use strict';
const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
const ios=()=>/iphone|ipad|ipod/i.test(navigator.userAgent);
const android=()=>/android/i.test(navigator.userAgent);
const mobile=()=>ios()||android()||matchMedia('(max-width:760px)').matches;
const prefix=()=>document.body.dataset.assetPrefix||'';
let deferredInstall=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});
function make(html,kind=''){const o=document.createElement('div');o.className='monubi-overlay '+kind;o.innerHTML='<section class="monubi-modal">'+html+'</section>';document.body.appendChild(o);return o}
function steps(){if(ios())return '<div class="install-steps"><div><b>1</b><span>Apri NUBEMO in <strong>Safari</strong>.</span></div><div><b>2</b><span>Tocca <strong>Condividi</strong> <i>⇧</i>.</span></div><div><b>3</b><span>Scegli <strong>Aggiungi alla schermata Home</strong>.</span></div></div>';if(android())return '<div class="install-steps"><div><b>1</b><span>Apri il menu del browser <strong>⋮</strong>.</span></div><div><b>2</b><span>Scegli <strong>Installa app</strong> o <strong>Aggiungi a schermata Home</strong>.</span></div><div><b>3</b><span>Conferma l’installazione.</span></div></div>';return '<p class="monubi-modal-lead">Dal menu del browser scegli <strong>Installa app</strong> oppure <strong>Aggiungi alla schermata Home</strong>.</p>'}
function installGuide(manual=false){if(standalone()&&!manual)return;const o=make('<button class="monubi-x">×</button><div class="modal-brand"><img src="'+prefix()+'assets/nubemo-brand-clean-v2.png"><div><strong>NUBEMO</strong><span>Il tuo percorso, ogni giorno.</span></div></div><div class="modal-kicker">PORTALA CON TE</div><h2>NUBEMO sul dispositivo,<br>come una vera app.</h2><p class="monubi-modal-lead">Nessun download dallo store: la aggiungi alla Home e continui a usare gli stessi dati.</p>'+steps()+'<div class="modal-actions">'+(deferredInstall?'<button class="primary monubi-install-now">Installa NUBEMO</button>':'')+'<button class="secondary monubi-close">Ho capito</button></div>','install');o.querySelector('.monubi-x').onclick=o.querySelector('.monubi-close').onclick=()=>o.remove();o.querySelector('.monubi-install-now')?.addEventListener('click',async()=>{try{deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;o.remove()}catch(e){}})}
window.showNubemoInstallGuide=()=>installGuide(true);window.showMonubiInstallGuide=window.showNubemoInstallGuide;
function hasOldData(){try{return Object.keys(localStorage).some(k=>k.startsWith('diario'))}catch(e){return false}}
function migration(){const key='monubi-migration-v2-seen';if(!hasOldData()||localStorage.getItem(key))return;localStorage.setItem(key,'1');const o=make('<div class="migration-orb"></div><div class="modal-brand migration-brand"><img src="'+prefix()+'assets/nubemo-brand-clean-v2.png"><div><strong>NUBEMO</strong><span>MOdena · NUtrizione · BIenessere</span></div></div><div class="modal-kicker">NUOVA IDENTITÀ</div><h2>Diario diventa<br><em>NUBEMO.</em></h2><p class="monubi-modal-lead">È cambiata l’esperienza, non il tuo percorso. <strong>I dati che avevi già inserito sono ancora qui.</strong></p><div class="migration-badges"><span>✓ Stessi dati</span><span>✓ Stesse funzioni</span><span>✓ Nuovo design</span></div><div class="modal-actions"><button class="primary monubi-enter">Entra in NUBEMO</button>'+(standalone()?'<button class="secondary monubi-icon-info">Info nuova icona</button>':'')+'</div>','migration');o.querySelector('.monubi-enter').onclick=()=>o.remove();o.querySelector('.monubi-icon-info')?.addEventListener('click',()=>{o.remove();const h=make('<button class="monubi-x">×</button><div class="modal-kicker">NUOVA ICONA</div><h2>Vedi ancora l’icona di Diario?</h2><p class="monubi-modal-lead">Il telefono può conservarla in cache. <strong>Prima crea un backup dall’app</strong>. Poi apri lo stesso indirizzo nel browser e aggiungi NUBEMO nuovamente alla Home.</p><button class="secondary monubi-close">Chiudi</button>');h.querySelector('.monubi-x').onclick=h.querySelector('.monubi-close').onclick=()=>h.remove()})}
function nudge(){if(!mobile()||standalone())return;const key='monubi-install-nudge-v2';if(localStorage.getItem(key))return;setTimeout(()=>{localStorage.setItem(key,'1');installGuide()},1700)}
document.addEventListener('DOMContentLoaded',()=>{setTimeout(migration,280);setTimeout(nudge,600)})
})();
