// NUBEMO — Area Professionista / Visite paziente
(() => {
  'use strict';
  const services = window.nubemoProfessionalServices;
  const patients = window.nubemoProfessionalPatients;
  if (!services || !patients) return;

  const cache = new Map();
  const esc = (v='') => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  const pid = () => patients.getCurrentPatientId?.() || '';
  const isVisits = () => document.body.dataset.proView === 'details' && !!document.querySelector('[data-patient-tab="visits"].active');
  const active = () => patients.getPatientById?.(pid())?.relationship?.status !== 'ended';
  const fmt = v => { const d=new Date(v); return Number.isNaN(d.getTime())?esc(v):d.toLocaleString('it-IT',{dateStyle:'short',timeStyle:'short'}); };

  function host(){return document.querySelector('.patient-content-card');}
  function replace(patientId, html, sig, bind){const card=host();if(!card)return;const old=document.getElementById('nubemoProfessionalVisits');if(old&&old.dataset.patientId===patientId&&old._sig===sig){bind?.(old);return;}const head=card.querySelector(':scope > .patient-section-head');Array.from(card.children).forEach(c=>{if(c!==head)c.remove();});const b=document.createElement('div');b.id='nubemoProfessionalVisits';b.dataset.patientId=patientId;b._sig=sig;b.innerHTML=html;card.appendChild(b);bind?.(b);}
  async function load(patientId,force=false){if(!force&&cache.has(patientId))return cache.get(patientId);const rows=await services.loadPatientAppointments(patientId);cache.set(patientId,rows||[]);return rows||[];}
  function html(rows,canEdit){return `<div class="section-head"><h2>Visite</h2>${canEdit?'<button class="mini" id="nubemoNewVisit">＋ Nuova visita</button>':''}</div>${rows.length?rows.map(r=>`<div class="pro3-event"><b>${fmt(r.starts_at)}</b><span>${esc(r.appointment_type||'Visita')} · ${esc(r.status||'')}</span>${r.notes?`<span>${esc(r.notes)}</span>`:''}${canEdit?`<button class="mini" data-edit-visit-id="${esc(r.id)}">Modifica</button>`:''}</div>`).join(''):'<p class="muted">Nessuna visita.</p>'}`;}
  function render(patientId,rows){const canEdit=active();replace(patientId,html(rows,canEdit),JSON.stringify(rows),h=>{h.querySelector('#nubemoNewVisit')?.addEventListener('click',()=>openEditor(patientId,null));h.querySelectorAll('[data-edit-visit-id]').forEach(b=>b.addEventListener('click',()=>openEditor(patientId,rows.find(r=>r.id===b.dataset.editVisitId))));});}
  function localValue(iso){if(!iso)return '';const d=new Date(iso);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16);}
  function openEditor(patientId,existing){if(!active())return alert('Paziente attivo non disponibile.');const o=document.createElement('div');o.className='clinical-overlay';o.id='patientVisitOverlay';const start=existing?localValue(existing.starts_at):`${new Date().toISOString().slice(0,10)}T09:00`;const end=existing?localValue(existing.ends_at):`${new Date().toISOString().slice(0,10)}T10:00`;o.innerHTML=`<section class="clinical-modal"><button class="monubi-x" id="closeVisit">×</button><div class="eyebrow">VISITE</div><h2>${existing?'Modifica visita':'Nuova visita'}</h2><label>Inizio</label><input id="visitStart" type="datetime-local" value="${esc(start)}"><label>Fine</label><input id="visitEnd" type="datetime-local" value="${esc(end)}"><label>Tipo</label><input id="visitType" value="${esc(existing?.appointment_type||'Visita')}"><label>Stato</label><select id="visitStatus"><option value="scheduled" ${existing?.status==='scheduled'?'selected':''}>Programmato</option><option value="completed" ${existing?.status==='completed'?'selected':''}>Completato</option><option value="cancelled" ${existing?.status==='cancelled'?'selected':''}>Annullato</option></select><label>Note</label><textarea id="visitNotes" rows="4">${esc(existing?.notes||'')}</textarea><div class="pro3-actions"><button class="secondary" id="cancelVisit">Annulla</button><button class="primary" id="saveVisit">Salva</button></div></section>`;document.body.appendChild(o);const close=()=>o.remove();o.querySelector('#closeVisit')?.addEventListener('click',close);o.querySelector('#cancelVisit')?.addEventListener('click',close);o.addEventListener('click',e=>{if(e.target===o)close();});o.querySelector('#saveVisit')?.addEventListener('click',async()=>{const b=o.querySelector('#saveVisit'),s=o.querySelector('#visitStart')?.value,e=o.querySelector('#visitEnd')?.value;if(!s||!e)return alert('Inserisci data e ora di inizio e fine.');const sd=new Date(s),ed=new Date(e);if(ed<=sd)return alert('L’orario di fine deve essere successivo all’inizio.');const values={startsAt:sd.toISOString(),endsAt:ed.toISOString(),appointmentType:String(o.querySelector('#visitType')?.value||'').trim()||null,status:o.querySelector('#visitStatus')?.value||'scheduled',notes:String(o.querySelector('#visitNotes')?.value||'').trim()||null};if(b){b.disabled=true;b.textContent='Salvataggio...';}try{if(existing)await services.updatePatientAppointment(existing.id,values);else await services.createPatientAppointment(patientId,values);close();render(patientId,await load(patientId,true));}catch(err){console.error('NUBEMO visit save',err);alert('Non è stato possibile salvare la visita.');}finally{if(b){b.disabled=false;b.textContent='Salva';}}});}
  async function syncView(){if(!isVisits())return;const patientId=pid();if(!patientId)return;replace(patientId,'<p class="muted">Caricamento visite...</p>','loading');try{const rows=await load(patientId);if(isVisits()&&pid()===patientId)render(patientId,rows);}catch(e){console.error('NUBEMO visits load',e);replace(patientId,'<p class="muted">Non è stato possibile caricare le visite.</p>','error');}}
  window.nubemoProfessionalAgenda=Object.freeze({syncView,reload:async(patientId=pid())=>{if(patientId)render(patientId,await load(patientId,true));},openEditor});
})();
